version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  tests:
    docker:
      - image: circleci/node:16.13.0-browsers
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - node/install-packages
      - run: npm run lint
      - run: npm run cover

workflows:
  ci:
    jobs:
      - tests
