version: 2.1

orbs:
  node: circleci/node@4.7.0
  codecov: codecov/codecov@1.0.2

jobs:
  tests:
    docker:
      - image: circleci/node:16.13.0-browsers
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - node/install-packages
      - run: npm run lint
      - run: npm run cover
      - codecov/upload:
          file: coverage/*.json
  versioning:
    docker:
      - image: circleci/node:16.13.0-browsers
    steps:
      - checkout
      - run:
          name: Check package version
          command: node scripts/check-version kmuchau1 autoescola
workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
